name: Integrarion Tests for Final Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: unittest
      run: python3 -m unittest discover -v
    - name: More integration test
      run: |
        cp test/integration_test.py .
        python3 integration_test.py
